### PR TITLE
Ez pages in 1.5.6 have new db structure

### PR DESCRIPTION
**Pull request by danielllek**
Add new query for 1.5.6 ez pages title. 

EZ pages in 1.5.6 has split data to new table.

### CODE REVIEW

**Comment by jeking928** [comment]
@danielllek Just asking, did you test this? I did on ZC 1.5.6 with PHP 5.6 and get an error after installation.

[26-Dec-2018 19:48:37 America/Chicago] PHP Fatal error:  1054:Unknown column 'pages_title' in 'field list' :: SELECT `pages_id` AS `id`, `pages_title` AS `name` FROM `ezpages` ==> (as called by) /public_html/zencart156/includes/classes/usu.php on line 1054 <== in /public_html/zencart156/includes/classes/db/mysql/query_factory.php on line 171

**Comment by jeking928** [comment]
This should fix it. One lines 1044 and 1051 of the new usu.php, change TABLE_EZPAGES to TABLE_EZPAGES_CONTENT

I'll make a PR but since my file has danielllek changes and mine, not sure of that will mess it up.

**Comment by danielllek** [comment]
@jeking928 I tested, but I'm using some custom template and only this change fix was needed for my setup. 

Thanks for noticing and next PR :)

**Comment by danielllek** [comment]
I'm closing this, because more complete PR is #4

**Comment by lat9** [comment]
@daneilllek, I've re-opened this issue so that I've got "visibility" to track the change submitted by @jeking928 for the next USU release.

**Pull request merged**
